### ISSUE TITLE
Add Trophée Jules Verne overlay

### ISSUE THREAD

**Issue by Rhmaric** [volodiaja/race_tracker#4]
Hi !
Thank a lot for this great work !

I don't know if it's the right place to create this issue...
But it would be so nice to have an overlay to display on your website https://volodiaja.net/Tracking/ the position of Sodebo and Gitana in their Trophée Jules Verne record attempt !

Do you think this is feasible?

**Comment by jachenilleau** [comment]
Hi,
Thanks, but that's out of our reach (and slightly out of the project scope). 
Teams are refusing to appear on the map, and their data are not easy to access (even if they are accessible).

**Comment by Rhmaric** [comment]
Hello,
Ok, I understand your point.

As a personal project, i would like to dig into it anyway. What do you mean by "accessible" ? Is there a more convenient way to access this data than scrapping each individual website ?
